version: '3.7'

services:
  app:
    build: .
    command: flask run --host=0.0.0.0
    environment:
      - SOUNDS_PER_PAGE=10
      - CHUNK_NUMBER=17
    ports:
      - "5000:5000"
    stop_signal: SIGINT
    volumes:
      - .:/app
      - /home/pablo/data/17:/app/static/tracks
